INSERT INTO specializations (name) VALUES
('Acompañante Terapéutico'),
('Acupuntura'),
('Alergología'),
('Análisis Clínicos'),
('Análisis de Sangre'),
('Anatomía Patológica'),
('Andrología'),
('Anestesiología'),
('Asesoría Lactancia Materna'),
('Audiología'),
('Bioquímica'),
('Cardiología'),
('Cardiología Infantil'),
('Cirugía Bariátrica'),
('Cirugía de cabeza y cuello'),
('Cirugía Cardiovascular'),
('Cirugía General'),
('Cirugía Ginecológica'),
('Cirugia Infantil'),
('Cirugía Oncológica'),
('Cirugía Plástica'),
('Clínica Médica'),
('Clínica Quirúrgica'),
('Cosmetología'),
('Dermatología'),
('Dermatología Infantil'),
('Diabetología'),
('Diagnóstico por Imágenes'),
('Ecografía'),
('Ecografía Vesicoprostática'),
('Endocrinología'),
('Endocrinología Ginecológica'),
('Endocrinología Infantil'),
('Estética'),
('Estomatología'),
('Fertilidad'),
('Fisiatría'),
('Flebología'),
('Fonoaudiología'),
('Gastroenterología'),
('Gastroenterología Infantil'),
('Genética'),
('Geriatría'),
('Ginecología'),
('Guardia'),
('Hematología'),
('Hematología y hemoterapia'),
('Hemoterapia'),
('Hepatología'),
('Hidrología médica'),
('Infectología'),
('Inmunología'),
('Kinesiología'),
('Kinesiología Infantil'),
('Kinesiología Oncologica'),
('Kinesiología Pediátrica'),
('Laboratorios Clínicos'),
('Lactancia'),
('Linfología'),
('Masajista'),
('Mastología'),
('Medicina Aeroespacial'),
('Medicina Cannabica'),
('Medicina China'),
('Medicina de urgencias'),
('Medicina del deporte'),
('Medicina del Dolor'),
('Medicina del Estrés'),
('Medicina del trabajo'),
('Medicina Estética'),
('Medicina familiar y comunitaria'),
('Medicina física y rehabilitación'),
('Medicina General'),
('Medicina Integrada'),
('Medicina intensiva'),
('Medicina Interna'),
('Medicina Legal'),
('Medicina legal y forense'),
('Medicina paliativa'),
('Medicina preventiva y salud pública'),
('Medicina Regenerativa'),
('Mesoterapia Corporal'),
('Nefrología'),
('Nefrología Infantil'),
('Neonatología'),
('Neumologia'),
('NeumonologÍa'),
('Neumonología Infantil'),
('Neurocirugia'),
('Neurología'),
('Neurología Infantil'),
('Nutrición'),
('Nutrición Bariátrica'),
('Nutrición Deportiva'),
('Nutrición Infantil'),
('Obstetricia'),
('Odontología'),
('Oftalmología'),
('Oftalmología Infantil'),
('Oncología'),
('Ortodoncia'),
('Ortodoncia Infantil'),
('Ortopedia'),
('Ortopedia Infantil'),
('Otoneurología'),
('Otorrinolaringología'),
('Otorrinolaringología Infantil'),
('Patología Mamaria'),
('Pediatría'),
('Periodoncia'),
('Podología'),
('Proctología'),
('Proloterapia'),
('Psicología'),
('Psicología Infantil'),
('Psicopedagogía'),
('Psicopedagogía Infantil'),
('Psiquiatría'),
('Puericultura'),
('Radiología'),
('Radioterápica'),
('Reumatología'),
('Reumatología Infantil'),
('Sexología'),
('Terapia Ocupacional'),
('Tocoginecología'),
('Toxicología'),
('Tratamiento del Dolor'),
('Traumatología'),
('Uroginecología'),
('Urología'),
('Vacunación');